- import_role:
    name: cypreess.postgres

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Install PostgreSQL
  apt: name={{ base_python_package }}-psycopg2 update_cache=yes state=present

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{ application_db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure user has access to the database
  become: yes
  become_user: postgres
  postgresql_user: db={{ application_db_name }}
                   name={{ application_db_user }}
                   password={{ application_db_password }}
                   encrypted=yes
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  become: yes
  become_user: postgres
  postgresql_user: name={{ application_db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present


- name: Accept md5 passwords
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    regexp: '^host all all all md5'
    line: "host all all all md5"
  notify: reload postgresql

- name: Expose postgres to network
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^listen_addresses'
    line: "listen_addresses='*'"
  notify: restart postgresql
